development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: big_data_server_development
  pool: 25
  timeout: 5
  username: big-things
  password: B!GD@ta

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: big_data_server_test
  pool: 25
  timeout: 5
  username: big-things
  password: B!GD@ta
